name: test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install
        run: yarn install

      - name: lint
        run: yarn lint:style

      - name: docs
        run: yarn docs:build
      
      - name: build
        run: yarn build
